CREATE DATABASE IF NOT EXISTS NuxtChat CHARACTER SET 'utf8';

CREATE USER IF NOT EXISTS 'localNuxt'@'localhost' IDENTIFIED BY 'localPassword';

USE NuxtChat;

GRANT SELECT, INSERT, DELETE, UPDATE ON * TO 'localNuxt'@'localhost';

#user schema
CREATE TABLE IF NOT EXISTS users (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	pseudo VARCHAR(15) NOT NULL UNIQUE,
	password TEXT NOT NULL,
	refreshToken TEXT UNIQUE
);

#friends schema
CREATE TABLE IF NOT EXISTS friends (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userId SMALLINT UNSIGNED NOT NULL,
	friendId SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT fk_friends_user_userId FOREIGN KEY (userId) REFERENCES users(id),
	CONSTRAINT fk_friends_user_friendId FOREIGN KEY (friendId) REFERENCES users(id)
);

#message shcema
CREATE TABLE IF NOT EXISTS messages (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userId SMALLINT UNSIGNED NOT NULL,
	friendId SMALLINT UNSIGNED NOT NULL,
	message TEXT,
	creation DATETIME DEFAULT NOW()
	CONSTRAINT fk_message_user_userId FOREIGN KEY (userId) REFERENCES users(id),
	CONSTRAINT fk_message_user_friendId FOREIGN KEY (friendId) REFERENCES users(id)
);

