CREATE DATABASE IF NOT EXISTS NuxtChat CHARACTER SET 'utf8';

CREATE USER IF NOT EXISTS 'localNuxt'@'localhost' IDENTIFIED BY 'localPassword';

USE NuxtChat;

GRANT SELECT, INSERT, DELETE, UPDATE ON * TO 'localNuxt'@'localhost';

#user shema
CREATE TABLE IF NOT EXISTS users (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	pseudo VARCHAR(15) NOT NULL UNIQUE,
	password TEXT NOT NULL,
	image VARCHAR(30) NOT NULL DEFAULT 'default.png'
);